const XLSX = require("xlsx");
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.aoa_to_sheet([["hours"], [0.1875]]);
ws.A2.t = 'n';
ws.A2.z = 'h:mm';
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
const buf = XLSX.write(wb, { type: "buffer" });
const readWb = XLSX.read(buf, { cellDates: true });
const readWs = readWb.Sheets["Sheet1"];
const json = XLSX.utils.sheet_to_json(readWs);
const val = json[0].hours;
console.log("val instanceof Date?", val instanceof Date);
console.log("val is:", val);
console.log("getHours():", val.getHours());
console.log("getMinutes():", val.getMinutes());
console.log("getUTCHours():", val.getUTCHours());
console.log("getUTCMinutes():", val.getUTCMinutes());
